version: "3.8"

services:
  test: &base
    working_dir: /app/
    build:
      context: .
      target: dependencies
    command: "yarn test"
    volumes:
      - .:/app/

  coverage:
    <<: *base
    command: yarn test --coverage --watchAll false

  install:
    <<: *base
    command: "yarn"

  app:
    <<: *base
    command: "yarn start"
    ports:
      - 3000:3000
